services:
  db:
    image: 'postgres:13.3'
    environment:
      - 'POSTGRES_DB=warehouse'
      - 'POSTGRES_PASSWORD=danila'
      - 'POSTGRES_USER=danila'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
