services:
  db:
    image: 'postgres:13.3'
    environment:
      - 'POSTGRES_DB=${DATABASE_DB}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${DATABASE_USERNAME}'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - 'DATABASE_HOST=db'
      - 'DATABASE_PORT=${DATABASE_PORT}'
      - 'DATABASE_DB=${DATABASE_DB}'
      - 'DATABASE_USERNAME=${DATABASE_USERNAME}'
      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
    ports:
      - "8189:8189"