version: "3.7"
networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
    driver: local

services:
  db:
    image: 'postgres:13.3'
    networks:
      - app-network
    environment:
      - 'POSTGRES_DB=${DATABASE_DB}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${DATABASE_USERNAME}'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - app-network
    environment:
      - 'DATABASE_HOST=db'
      - 'DATABASE_PORT=${DATABASE_PORT}'
      - 'DATABASE_DB=${DATABASE_DB}'
      - 'DATABASE_USERNAME=${DATABASE_USERNAME}'
      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
    ports:
      - "8189:8189"
    links:
      - db

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - app-network
    environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio