spring:
  config:
   import: file:./.env[.properties],file:.env[.properties]

  application:
    name: warehouse
    current-profile: postgres

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: ${APP_PORT:8189}
  servlet:
    context-path: /api/v0/

app:
  scheduling:
    enable: true
    optimize: false
    interval: 60000
    rate: 1.1
    pessimistic-lock: false
  batch:
    size: 50000
