rest:
  currency-service:
    host: http://localhost:8081
    filePath: exchange-rate.json
    mock: false
    methods:
      get-currency: /api/v1/currencies

spring:
  profiles:
    active: postgres
  cache:
    cache-names: currencyRates
    caffeine:
      spec: maximumSize=500, expireAfterAccess=60s

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}