rest:
  currency-service:
    host: http://localhost:8081
    filePath: exchange-rate.json
    mock: false
    methods:
      get-currency: /api/v1/currencies

kafka:
  enabled: ${KAFKA_ENABLE:true}
  url: ${KAFKA_URL:localhost:9091}
  groupId: ${KAFKA_CONSUMER_CROUP_ID:group1}

spring:
  profiles:
    active: h2
  cache:
    cache-names: currencyRates
    caffeine:
      spec: maximumSize=500, expireAfterAccess=60s
